<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>syntax highlight with correct scopes for magik</string>
	<key>fileTypes</key>
	<array>
		<string>magik</string>
		<string>Magik</string>
		<string>MAGIK</string>
	</array>
	<key>firstLineMatch</key>
	<string>^#%.*\b</string>
	<key>foldingStartMarker</key>
	<string>^(_block|_catch|_if|_elif|_else|_lock|_loop|_method|_proc|_protect|_try)</string>
	<key>foldingStopMarker</key>
	<string>^(_endblock|_endcatch|_endif|_endlock|_endloop|_endmethod|_endproc|_endprotect|_endtry)</string>
	<key>keyEquivalent</key>
	<string>^~P</string>
	<key>name</key>
	<string>Magik</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.magik</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>comment.line.number-sign.magik</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>public comment, docstring</string>
			<key>match</key>
			<string>(##).*$\n?</string>
			<key>name</key>
			<string>comment.block.documentation.magik</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.magik</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>comment.line.number-sign.magik</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>encoding details</string>
			<key>match</key>
			<string>(#%).*$\n?</string>
			<key>name</key>
			<string>comment.encode.magik</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.magik</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>a single line comment</string>
			<key>match</key>
			<string>^(#)(?!((##)|(#%))).*$\n?</string>
			<key>name</key>
			<string>comment.line.number-sign.magik</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([1-9]+[0-9]*|0)\b</string>
			<key>name</key>
			<string>constant.numeric.integer.magik</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>radix integer - integer with any base, exponent form or float TODO split this</string>
			<key>match</key>
			<string>\b(\d+(?i:(e|r|\&amp;|\.))\d*)\b</string>
			<key>name</key>
			<string>constant.numeric.complex.magik</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>character literal like %a, %b ...</string>
			<key>match</key>
			<string>(%)(.)\b</string>
			<key>name</key>
			<string>constant.character.literal.magik</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>unicode character like %u000e ...</string>
			<key>match</key>
			<string>(%u)(.)+\b</string>
			<key>name</key>
			<string>constant.character.unicode.magik</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>character name like %newline ...</string>
			<key>match</key>
			<string>(%)(.)+\b</string>
			<key>name</key>
			<string>constant.character.unicode.magik</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>symbols like :a_symbol</string>
			<key>match</key>
			<string>(:)(\w+)\b</string>
			<key>name</key>
			<string>variable.other.symbol.magik</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>lebel or global variable expression</string>
			<key>match</key>
			<string>(\@\w+)\b</string>
			<key>name</key>
			<string>variable.other.label.magik</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>dynamic variable</string>
			<key>match</key>
			<string>(\!\w+)\b</string>
			<key>name</key>
			<string>variable.other.dynamic.magik</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>boolean variable</string>
			<key>match</key>
			<string>\b(\w+)(\?)</string>
			<key>name</key>
			<string>variable.other.bool.magik</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(:\|)</string>
			<key>comment</key>
			<string>symbols like :|a symbol|</string>
			<key>end</key>
			<string>(\|)</string>
			<key>name</key>
			<string>variable.other.symbol.canonical.magik</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tuple.begin.magik</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.empty-tuple.magik</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tuple.end.magik</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>simple vectors</string>
			<key>match</key>
			<string>(\{)(.*)(\})</string>
			<key>name</key>
			<string>meta.structure.vector.magik</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>keyword operators that evaluate to True or False</string>
			<key>match</key>
			<string>\b(_and|_andif|_not|_or|_orif|_xor)\b</string>
			<key>name</key>
			<string>keyword.operator.logical.magik</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(&lt;\=|&gt;\=|\=\=|&gt;|\!\=|_cf|_is|_isnt|&lt;&gt;)\b</string>
			<key>name</key>
			<string>keyword.operator.comparison.magik</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\+&lt;&lt;|-&lt;&lt;|\*&lt;&lt;|/&lt;&lt;</string>
			<key>name</key>
			<string>keyword.operator.assignment.augmented.magik</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\+|\-|\*|\*\*|/|\||\^|\~|(_div)|(_mod)</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.magik</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(&lt;&lt;)</string>
			<key>name</key>
			<string>keyword.operator.assignment.magik</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(_true|_false|_maybe|_unset|_no_way|_thisthread|_constant)\b</string>
			<key>name</key>
			<string>constant.language.magik</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(_self|_clone|_super)\b</string>
			<key>name</key>
			<string>variable.language.magik</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>keywords that delimit flow blocks or alter flow from within a block</string>
			<key>match</key>
			<string>\b(_leave|_elif|_else|_when|_for|_if|_try|_with|_continue|_return|_catch|_endcatch|_endif|_endlock|_endloop|_endprotect|_endtry|_lock|_loop|_loopbody|_over|_protect|_protection|_then)\b</string>
			<key>name</key>
			<string>keyword.control.flow.magik</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>functions</string>
			<key>match</key>
			<string>\b(_block|_method|_proc|_endblock|_endmethod|_endproc)\b</string>
			<key>name</key>
			<string>storage.type.function.magik</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>function modifiers</string>
			<key>match</key>
			<string>\b(_abstract|_iter|_private)\b</string>
			<key>name</key>
			<string>storage.modifier.magik</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>keywords that haven't fit into other groups (yet).</string>
			<key>match</key>
			<string>\b(_dynamic|_finally|_global|_handling|_import|_local|_recursive|_throw)\b</string>
			<key>name</key>
			<string>keyword.other.magik</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(_package)\s(\w+)</string>
			<key>name</key>
			<string>constant.language.package.magik</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>keywords that haven't fit into other groups (yet).</string>
			<key>match</key>
			<string>\b(_allresults|_scatter|_gather|_optional)\b</string>
			<key>name</key>
			<string>keyword.other.args.magik</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>keywords that haven't fit into other groups (yet).</string>
			<key>match</key>
			<string>\b(_pragma)\b</string>
			<key>name</key>
			<string>keyword.other.pragma.magik</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>standard procs</string>
			<key>match</key>
			<string>\b(write|print|show)\b</string>
			<key>name</key>
			<string>keyword.other.misc.magik</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>slots, functions that starts with .</string>
			<key>match</key>
			<string>(\.)([a-z]\w+)</string>
			<key>name</key>
			<string>entity.name.slot.magik</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\()</string>
			<key>end</key>
			<string>(\))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#string_quoted_single</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string_quoted_double</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>string_quoted_double</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(")</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.magik</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>double quoted string single line</string>
					<key>end</key>
					<string>((?&lt;=")(")|")|(\n)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.magik</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.empty-string.double.magik</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.unclosed-string.magik</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.magik</string>
				</dict>
			</array>
		</dict>
		<key>string_quoted_single</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(')</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.magik</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>single quoted string single line</string>
					<key>end</key>
					<string>((?&lt;=')(')|')|(\n)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.magik</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.empty-string.double.magik</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.unclosed-string.magik</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.magik</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_quoted_double</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_quoted_single</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.magik</string>
	<key>uuid</key>
	<string>a451e5fa-5ef0-47cb-8f77-57d09e40b794</string>
</dict>
</plist>
