<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>magik</string>
		<string>Magik</string>
		<string>MAGIK</string>
	</array>
	<key>name</key>
	<string>Magik</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#docstrings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#encodings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#blocks</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#builtins</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#methods</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numbers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#packages</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings_</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#symbols</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#booleans</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>booleans</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>variable.other.magik</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([a-zA-Z]+(([0-9]|_|-|[a-zA-Z])*)\?)</string>
			<key>name</key>
			<string>variable.other.magik</string>
		</dict>
		<key>builtins</key>
		<dict>
			<key>include</key>
			<string>#self</string>
			<key>match</key>
			<string>\b(def_slotted_exemplar|def_package|define_shared_constant)\b</string>
			<key>name</key>
			<string>support.function.magik</string>
		</dict>
		<key>chars</key>
		<dict>
			<key>begin</key>
			<string>(%)</string>
			<key>end</key>
			<string>(\s+)</string>
			<key>name</key>
			<string>constant.character.magik</string>
		</dict>
		<key>comments</key>
		<dict>
			<key>begin</key>
			<string>(#)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.magik</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line.number-sign.magik</string>
		</dict>
		<key>docstrings</key>
		<dict>
			<key>begin</key>
			<string>(##)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.number-sign.magik</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.block.documentation.magik</string>
		</dict>
		<key>encodings</key>
		<dict>
			<key>begin</key>
			<string>(#%)</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line.percentage.magik</string>
		</dict>
		<key>illegal</key>
		<dict>
			<key>match</key>
			<string>([^\s}])</string>
			<key>name</key>
			<string>invalid.illegal.unrecognized.magik</string>
		</dict>
		<key>keywords</key>
		<dict>
			<key>match</key>
			<string>\b(\_[a-zA-Z]+)\b</string>
			<key>name</key>
			<string>keyword.control.magik</string>
		</dict>
		<key>methods</key>
		<dict>
			<key>begin</key>
			<string>(\w+)\s*\(</string>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>entity.name.function.magik</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#blocks</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#symbols</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#packages</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numbers</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#builtins</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings_</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#docstrings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#parameters</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#self</string>
				</dict>
			</array>
		</dict>
		<key>numbers</key>
		<dict>
			<key>match</key>
			<string>\b[0-9]+\b</string>
			<key>name</key>
			<string>constant.numeric.magik</string>
		</dict>
		<key>operators</key>
		<dict>
			<key>match</key>
			<string>([&lt;&lt;|&gt;&gt;|\-|\+|\*|/|=|&lt;&gt;|~])</string>
			<key>name</key>
			<string>keyword.operator.magik</string>
		</dict>
		<key>packages</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.other.magik</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.magik</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\w+:\w+)|((_package)\s(\w+))</string>
			<key>name</key>
			<string>storage.modifier.magik</string>
		</dict>
		<key>parameters</key>
		<dict>
			<key>match</key>
			<string>\w+</string>
			<key>name</key>
			<string>variable.parameter.magik</string>
		</dict>
		<key>self</key>
		<dict>
			<key>match</key>
			<string>\b(_self)\b</string>
			<key>name</key>
			<string>variable.language.magik</string>
		</dict>
		<key>strings</key>
		<dict>
			<key>begin</key>
			<string>(\")</string>
			<key>end</key>
			<string>(\")</string>
			<key>name</key>
			<string>string.quoted.double.magik</string>
		</dict>
		<key>strings_</key>
		<dict>
			<key>begin</key>
			<string>(\')</string>
			<key>end</key>
			<string>(\')</string>
			<key>name</key>
			<string>string.quoted.single.magik</string>
		</dict>
		<key>symbols</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>constant.other.symbol.magik</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(:[a-zA-Z]+(([0-9]|_|-|[a-zA-Z])*))</string>
			<key>name</key>
			<string>variable.other.magik</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.magik</string>
	<key>uuid</key>
	<string>a451e5fa-5ef0-47cb-8f77-57d09e40b794</string>
</dict>
</plist>
